### ISSUE TITLE
Cannot drag-and-drop when in "create" mode

### ISSUE THREAD

**Issue by mariomadproductions** [marco-calautti/DeltaPatcher#1]
You cannot drag-and-drop when in "create" mode. Could this be added/fixed?

**Comment by marco-calautti** [comment]
Yes it can definitely be added. I will try to do something in the next days.

**Comment by marco-calautti** [comment]
So, I had some time today :P. Can you please test this version and tell me if it works as expected?
https://mega.nz/#!m4plTCTa!hhUD5E2kcpb-eFHPkd7HK9UYGQbGRT7hAswjviastPk

**Comment by mariomadproductions** [comment]
That works fine. Thanks.

**Comment by marco-calautti** [comment]
Fixed.
