### ISSUE TITLE
Marked as Malware by Antivirus

### ISSUE THREAD

**Issue by pifase** [marco-calautti/DeltaPatcher#17]
Hello, I would like to report that both Malwarebytes and Virustotal are marking the program as Malware.
![Virustotal](https://user-images.githubusercontent.com/58706631/191815468-93584adb-ed2d-404b-b07e-79a0684baa5c.png)

![Malwarebytes](https://user-images.githubusercontent.com/58706631/191815422-97f37649-82b4-4a1c-8e3f-70196a3833da.png)

**Comment by marco-calautti** [comment]
Are you referring to the old 2.0 version? The new version (3.0) should not have this issue

**Comment by marco-calautti** [comment]
You can download the new version from the releases section. There are builds for windows, Linux, and MacOS as well.

**Comment by pifase** [comment]
Oh, whoops. I didn't even realize that I was using an outdated version
