### ISSUE TITLE
 slight problem

### ISSUE THREAD

**Issue by CertifiedFemboy** [marco-calautti/DeltaPatcher#18]
Every time I try to open DeltaPatcher, my computer says "operation did not complete successfully because the file contains a virus or potentially unwanted software." 
![image](https://user-images.githubusercontent.com/121648768/210025786-20b97dc8-dd1f-4501-8302-ad6226f1bc63.png)
Can anyone help me fix this?

**Comment by CertifiedFemboy** [comment]
I've even tried to turn off my firewall and it doesn't fix it.

**Comment by marco-calautti** [comment]
Please download the latest version from the release page. You are using an old version.
