### ISSUE TITLE
Old Version of MacOS.

### ISSUE THREAD

**Issue by Supersasdasdasd** [marco-calautti/DeltaPatcher#19]
It says, "You can’t use this version of the application “DeltaPatcher” with this version of macOS." "You have macOS 10.13.6. The application requires macOS 10.14 or later." How can I run this app?

**Comment by marco-calautti** [comment]
The message is quite clear. You need at least macOS 10.14 to run it.  You need to update your system. I have no means to build DeltaPatcher for an older version of macOS.

**Comment by Supersasdasdasd** [comment]
I can't

**Comment by Supersasdasdasd** [comment]
My Mac's from 2011

**Comment by Supersasdasdasd** [comment]
It can't update past 10.13.6.

**Comment by marco-calautti** [comment]
The I would suggest following the instructions in the main github page on how to compile it from sources. I do not have a Mac available to do it myself

**Comment by marco-calautti** [comment]
If you are just looking for a way to apply an xdelta patch on Mac, you can try this https://github.com/Sappharad/MultiPatch

This is another xdelta patcher for Mac, that should work from macOS 10.9 onwards.

**Comment by marco-calautti** [comment]
> It can't update past 10.13.6.

@Supersasdasdasd I managed to build the latest version of Delta Patcher for macos 10.13. Delta Patcher should now work also on Macs from 2011.
