### ISSUE TITLE
"An error has occurred: xdelta3: too many filenames: -f ..."

### ISSUE THREAD

**Issue by mariomadproductions** [marco-calautti/DeltaPatcher#2]
When I try to patch a ROM, I get this error:
``An error has occurred: xdelta3: too many filenames: -f ...``
I've tried other programs (including xdelta command line) with no avail.

**Comment by marco-calautti** [comment]
Please, do not upload copyrighted material. Anyway, I tried applying the patch and it works perfectly fine on my machine. Check that your ROM is not read-only and the paths in which the rom and the patch are stored do not contain any special character.
