### ISSUE TITLE
cmake --build build --config Release --parallel (as recommended in readme) crashes terminal during build

### ISSUE THREAD

**Issue by anonaddict** [marco-calautti/DeltaPatcher#20]
cmake --build build --config Release --parallel nukes my computer 
It built fine when i removed the --parallel tag

**Comment by marco-calautti** [comment]
You might not have enough ram/cpu cores. What are your PC specs?

**Comment by marco-calautti** [comment]
Does it work if you use --parallel 2? Or with any small number of jobs?

**Comment by marco-calautti** [comment]
Anyway, I removed the --parallel from the readme.
