### ISSUE TITLE
An error has occurred: xdelta3: target window checksum mismatch: XD3_INVALID_INPUT

### ISSUE THREAD

**Issue by delta0890** [marco-calautti/DeltaPatcher#22]
so basically i tried patching pizza tower scoutdigo data.win with soundigo.xdelta
it doesn't work, it just logs [8:48:07 PM] An error has occurred: xdelta3: target window checksum mismatch: XD3_INVALID_INPUT

**Comment by marco-calautti** [comment]
I am sorry to be rude, but I am tired of explaining for the 1000th time
what that error means. That is not a problem with Delta Patcher. There are
plenty of closed issues here in github discussing this error message, which
has exclusively to do with the patch you are using not being applied to the
right ROM.
Even googling  for the error message will give you the answer you are
looking for in the first 2-3 website.




Il lun 8 mag 2023, 14:49 delta ***@***.***> ha scritto:

**Comment by ElektroStudios** [comment]
Suggestion: catch that exact error message and translate it into something more... human readable or understandable, like for example the words you've said: "The patch you are using is not being applied to the right ROM".

**Comment by marco-calautti** [comment]
Yes, that is an improvement I had in mind to implement. Since I have some free time during this period, I might try to implement that.

**Comment by marco-calautti** [comment]
Latest release of Delta Patcher now provides a better message when the input file is wrong!
