### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by Nielsbishere** [marco-calautti/DeltaPatcher#3]
Please add https://github.com/wxWidgets/wxWidgets as submodule so it builds without having to manually clone it. I fetched it and it doesn't build. Also use $(SolutionDir) instead of direct paths in the sln file, never assume installation location.

**Comment by marco-calautti** [comment]
Thank you for opening the issues. Unfortunately I do not have much time left to work on this project, but I would be glad to accept a pull request fixing the issue!

**Comment by marco-calautti** [comment]
There is a completely new build system pushed to the repo. It should now be easier to compile.
