### ISSUE TITLE
It shows an error, but then deletes itself a few seconds later (both delta patcher and delta patcher lite is affected by this)

### ISSUE THREAD

**Issue by yourizuring** [marco-calautti/DeltaPatcher#4]
I am trying to patch an xdelta file, but it shows this error message: 'An error has occurred: xdelta3: target window checksum mismatch: XD3_INVALID_INPUT', and then after a few seconds, it deletes itself.
Please fix this asap. This is extremely urgent.

**Comment by marco-calautti** [comment]
There is nothing wrong with Delta patcher. Is the file you are trying to patch that does not correspond to the right file the patch was created for. there are plenty of issues opened on this repo complaining about the same thing, and it is always your file's fault, not Delta patcher's. Even the error message states it clearly: checksum mismatch, invalid input. Please verify that you are patching the right file that is meant for the xdelta patch you are using.
