### ISSUE TITLE
[Arch Linux] implicit declaration of function ‘lseek’; did you mean ‘fseek’?

### ISSUE THREAD

**Issue by fily-gif** [marco-calautti/DeltaPatcher#52]
Hello! I am trying to compile DeltaPatcher for Arch Linux, but after literally copy-pasting the commands (after insuring i have all the packages needed, of course), I get the error message in the title. I have absolutely no idea why this occurs and even after removing the folder and doing the commands again, the error still comes up.

**Comment by marco-calautti** [comment]
Very strange, I have been compiling on arch very often. Now I am not able to build it as well. There must have been an update to g++/gcc that now treats the implicit-function-declaration warning as an error. I will try fixing it. In the meanwhile, you can specify you want to treat the warning not as an error when compiling.
These are errors coming from compiling external libraries though.

**Comment by marco-calautti** [comment]
Can you try compiling from this branch: https://github.com/marco-calautti/DeltaPatcher/tree/fix-implicit-function-declaration

It should be working now on arch. Once the CI confirms it also works on Windows and macOS I will merge to the master branch. I don't think it is worth creating a new release for this fix.

**Comment by marco-calautti** [comment]
It seems everything compiles fine with the new changes. I merged to the master branch. I am closing the issue. Please open a new issue if something else pops up.
