### ISSUE TITLE
(Not Responding) Keeps Appearing on DeltaPatcher

### ISSUE THREAD

**Issue by te-agma-at** [marco-calautti/DeltaPatcher#6]
**How to reproduce the error:**
Step 1. Click the folder icon (with "Original file" on the left of the input field)
Step 2. Click some times
Step 3. You'll eventually see (Not Responding) on the window title ("Delta Patcher Lite (Not Responding)")
Step 4. Click a few more times
Step 5. See popup that says "is not responding" and choices present "Close the program" or "Wait the program to respond"
Step 6. Click "Close the program"
EDIT: Okay, so it turns out the same method happens with the "Select a file" window on trying to find the path to the original file to be patched (Do step 1, but wait a while, and then repeat steps 2-6 on the "Select a file" window)
EDIT 2: Also happens when selecting folder on "Select a file" window, but it takes longer to respond
EDIT 3: Ok... also happens when selecting ANOTHER folder, apparently, but now it takes EVEN LONGER!! I'm starting to think (Not Responding) always appears and you can't get rid of it for some reason...
EDIT 4: Happens YET AGAIN when selecting a file as the original.
EDIT 5: EDIT 2-4's (Not Responding) persists for XDelta patch selection
EDIT 6: Still persists on "Select a file window"
EDIT 7: YET AGAIN keeps persisting, see EDIT 5
EDIT 8: Seems like it STILL persists when it tells you "Applying patch, please wait... (don't panic!)" Strange that it tells me to not panic there, because (Not Responding) seems like a valid reason to panic.
EDIT 9: "Patch successfully applied"? (Not Responding) persists on that too!

**Comment by gregvp00** [comment]
Same problem on Windows 10 21H2

**Comment by marco-calautti** [comment]
Again, please check your antivirus/Windows Defender. It is 99% sure identifiying delta patcher as a virus, because its exe is compressed.

**Comment by gregvp00** [comment]
> Again, please check your antivirus/Windows Defender. It is 99% sure identifiying delta patcher as a virus, because its exe is compressed.

Appears to be something else, when Delta's tries to open the File explorer frozes every time I navigate or even opening/closing It. The fastest solution is to drop the file into the program.

**Comment by marco-calautti** [comment]
Point is, Delta Patcher does nothing special besides asking the OS to open a file dialog. One the dialog is open, delta Patcher has no control on it. It is purely managed by the OS.

This seems to be a common problem on come Windows 10 installations: https://superuser.com/questions/975648/windows-10-often-freezes-when-saving-or-opening-files

I would investigate in this direction.

**Comment by marco-calautti** [comment]
Could you please try the latest release? https://github.com/marco-calautti/DeltaPatcher/releases/tag/v3.0.0
