### ISSUE TITLE
This message appears when I open the application.

### ISSUE THREAD

**Issue by Unknown5629** [marco-calautti/DeltaPatcher#7]
I try opening the application and this appears. I don't know how to fix it please help.
![Screenshot 2022-06-26 185856](https://user-images.githubusercontent.com/76602042/175842004-1e76cbc4-192b-4f99-b944-df732fb25249.png)

**Comment by marco-calautti** [comment]
Does this happen with other applications on your system?

**Comment by marco-calautti** [comment]
Can you try the latest release?  https://github.com/marco-calautti/DeltaPatcher/releases/tag/v3.0.0
